apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    app: wordpress
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_PASSWORD
              # change this - must match mysql.yaml password
              value: test123
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            # name must match the volume name below
            - name: var-www-html
            # mount path within the container
            mountPath: /var/www/html
      volumes:
        - name: war-www-html
          hostPath:
            path: /data/wordpress
