apiVersion: v1
kind: Service
metadata:
  name: wpfrontend
  labels:
    name: wpfrontend
    heritage: helm
spec:
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wordpress
