apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    heritage: helm
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 2368
  selector:
    app: ghost
