apiVersion: v1
kind: ReplicationController
metadata:
  name: ghost
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:0.7.4
#          env:
#            - name: some_name
#              value: some_value
          ports:
          - containerPort: 2368
            name: http
          volumeMounts:
            - name: var-lib-ghost
              mountPath: /var/lib/ghost
      volumes:
        - name: var-lib-ghost
          gcePersistentDisk:
            pdName: ghost-disk1
            fsType: ext4
