apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  ports:
  # the port that this service should serve on
  - port: 5432
    targetPort: 5432
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: postgres
    role: backend
