apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: weave-scope-probe
  labels:
    heritage: helm
    k8s-app:  weave-scope-probe
spec:
  template:
    metadata:
      name:  weave-scope-probe
      labels:
        heritage: helm
        k8s-app:  weave-scope-probe
    spec:
      containers:
      - name:  weave-scope-probe
        image: weaveworks/scope:0.11.1
        # Replace cbr0 by docker0 if you don't use a kubernetes-specific bridge
        command: ["/home/weave/entrypoint.sh", "--no-app", "--probe.docker.bridge", "cbr0", "--probe.docker", "true", "--probe.proc.root", "weave-scope-app"]
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 50m
        env:
        - name: "DOCKER_BRIDGE"
          value: "cbr0"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
