name: deis-lite
home: https://github.com/deis/workflow
version: 2.0.0-pre-alpha
description: For testing only!
maintainers:
- Rimas Mocevicius <rimas@deis.com>
details: |-
  Deis-Lite is one node setup made to run on Kube-Solo App, it has a persistent setup.
  
  Deis (pronounced DAY-iss) is an open source PaaS that makes it easy to deploy
  and manage applications on your own servers. Deis builds on Kubernetes
  to provide a lightweight, Heroku-inspired workflow.
